name: owwatcher
base: core18
version: git
summary: Detects when world-writable files are created in a specified directory
description: |
    This tool monitors a directory of your choosing (usually /tmp) in real
    time. If any world-writable files or directories are created in the
    monitored directory, a notification is sent via the syslog protocol to a
    syslog server of your choosing. 

    This tool is not intended to detect any kind of malware or intrusion.
    Rather, it is a vulnerability research tool which alerts a researcher of
    potential symlink race or TOCTOU vulnerabilities as the researcher goes
    about their daily activities. In this way, the researcher takes a passive
    approach to discovering symlink race or TOCTOU vulnerabilities, rather than
    a more active approach (e.g. code audits.)

grade: stable
confinement: strict

plugs:
    hostfs:
        interface: system-files
        read:
            - /var/lib/snapd/hostfs

parts:
    owwatcher:
        plugin: python
        python-version: python3
        source: .

apps:
    owwatcher:
        command: bin/owwatcher
        plugs:
            - network
            - hostfs
            - log-observe
    owwatcherd:
        command: bin/owwatcher
        plugs:
            - network
            - hostfs
            - log-observe
        daemon: simple
