name: tmpwatcher
architectures:
    - build-on: [amd64, i386, arm64]
base: core18
version: git
summary: Detects when world-writable files are created in a specified directory
description: |
    This tool monitors a directory of your choosing (usually /tmp) in real
    time. If any world-writable files or directories are created in the
    monitored directory, a notification is sent via the syslog protocol to a
    syslog server of your choosing.

    This tool is not intended to detect any kind of malware or intrusion.
    Rather, it is a vulnerability research tool which alerts a researcher of
    potential symlink race or TOCTOU vulnerabilities as the researcher goes
    about their daily activities. In this way, the researcher takes a passive
    approach to discovering symlink race or TOCTOU vulnerabilities, rather than
    a more active approach (e.g. code audits.)

grade: stable
confinement: strict

parts:
    tmpwatcher:
        plugin: python
        python-version: python3
        source: .

plugs:
    network: null
    system-backup: null

apps:
    tmpwatcher:
        command: bin/tmpwatcher
    tmpwatcherd:
        command: bin/tmpwatcher -c /var/snap/tmpwatcher/current/tmpwatcher.conf
        daemon: simple
